language: android
dist: trusty
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.0
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository
    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest
