language: android
dist: trusty
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.0
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository
    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

